import { uniqueNamesGenerator, adjectives } from 'unique-names-generator';

const animalsEmojis = {
    'monkey': '🐒',
    'gorilla': '🦍',
    'orangutan': '🦧',
    'dog': '🐶',
    'poodle': '🐩',
    'wolf': '🐺',
    'fox': '🦊',
    'racoon': '🦝',
    'cat': '🐱',
    'lion': '🦁',
    'tiger': '🐯',
    'leopard': '🐆',
    'horse': '🐴',
    'unicorn': '🦄',
    'zebra': '🦓',
    'deer': '🦌',
    'bison': '🦬',
    'cow': '🐮',
    'ox': '🐂',
    'pig': '🐷',
    'boar': '🐗',
    'ram': '🐏',
    'goat': '🐐',
    'camel': '🐪',
    'llama': '🦙',
    'giraffe': '🦒',
    'elephant': '🐘',
    'mammoth': '🦣',
    'rhinoceros': '🦏',
    'hippopotamus': '🦛',
    'mouse': '🐭',
    'rat': '🐀',
    'hamster': '🐹',
    'rabbit': '🐰',
    'chipmunk': '🐿️',
    'beaver': '🦫',
    'hedgehog': '🦔',
    'bat': '🦇',
    'bear': '🐻',
    'koala': '🐨',
    'panda': '🐼',
    'sloth': '🦥',
    'otter': '🦦',
    'skunk': '🦨',
    'kangaroo': '🦘',
    'badger': '🦡',
    'turkey': '🦃',
    'chicken': '🐔',
    'rooster': '🐓',
    'bird': '🐦',
    'penguin': '🐧',
    'dove': '🕊️',
    'eagle': '🦅',
    'duck': '🦆',
    'swan': '🦢',
    'owl': '🦉',
    'dodo': '🦤',
    'flamingo': '🦩',
    'peacock': '🦚',
    'parrot': '🦜',
    'frog': '🐸',
    'crocodile': '🐊',
    'turtle': '🐢',
    'lizard': '🦎',
    'snake': '🐍',
    'dragon': '🐉',
    'sauropod': '🦕',
    't-rex': '🦖',
    'whale': '🐋',
    'dolphin': '🐬',
    'seal': '🦭',
    'fish': '🐟',
    'shark': '🦈',
    'octopus': '🐙',
    'snail': '🐌',
    'butterfly': '🦋',
    'bug': '🐛',
    'ant': '🐜',
    'honeybee': '🐝',
    'beetle': '🪲',
    'cricket': '🦗',
    'cockroach': '🪳',
    'spider': '🕷️',
    'scorpion': '🦂',
    'mosquito': '🦟',
    'fly': '🪰',
    'worm': '🪱',
    'crab': '🦀',
    'lobster': '🦞',
    'shrimp': '🦐',
    'squid': '🦑'
};

const animalsWithEmojis = Object.keys(animalsEmojis);

export const getAnimalEmoji = (animalName: string) => {
    return animalsEmojis[animalName];
}

export const generateUniqueName = () => {
  return uniqueNamesGenerator({
    dictionaries: [adjectives, animalsWithEmojis],
    separator: ' '
  });
};